apiVersion: apps/v1
kind: Deployment
metadata:
  name: stash
  namespace: stash
  labels:
    app: stash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash
  template:
    metadata:
      labels:
        app: stash
    spec:
      imagePullSecrets:
      - name: headless-commerce-package-access-token
      initContainers:
      - name: check-db-ready
        image: postgres:11.5
        command: ['sh', '-c', 'until pg_isready -h stash-db -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
      - name: stash
        image: ghcr.io/headless-commerce/stash
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /health/live
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 30
        env:
        - name: STASH_DB_USER
          value: 'expense_tracker'
        - name: STASH_DB_PASS
          valueFrom:
            secretKeyRef:
              name: stash-secrets
              key: dbPass
        - name: STASH_DB_HOST
          value: 'stash-db'
        - name: STASH_DB_POOL_SIZE
          value: '10'
        - name: STASH_READ_DB
          value: 'reads'
        - name: STASH_EVENT_DB
          value: 'events'
        - name: STASH_DNS_ADDR
          value: 'stash.moview.com.ng'
        - name: STASH_HTTP_PORT
          value: '4000'
        - name: TMDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: stash-secrets
              key: tmdbToken
        - name: STASH_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: stash-secrets
              key: secretKeyBase
---
kind: Service
apiVersion: v1
metadata:
  name: stash
  namespace: stash
spec:
  ports:
  - name: web
    port: 80
    targetPort: 4000
  selector:
    app: stash
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: stash-web
  namespace: stash
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`stash.local`)
    services:
    - name: stash
      port: 80
