apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: stash-secrets
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: stash-secrets
  data:
  - secretKey: dbPass
    remoteRef:
      key: secret/stash
      property: db_pass
  - secretKey: tmdbToken
    remoteRef:
      key: secret/stash
      property: tmdb_token
  - secretKey: secretKeyBase
    remoteRef:
      key: secret/stash
      property: key_base