apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: stash-secrets
  namespace: stash
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: stash-secrets
  data:
  - secretKey: dbPass
    remoteRef:
      key: secret/stash/db-pass
      property: value
  - secretKey: tmdbToken
    remoteRef:
      key: secret/stash/tmdb-token
      property: value
  - secretKey: secretKeyBase
    remoteRef:
      key: secret/stash/secret-key-base
      property: value